import React from 'react';

// =============================================================================

export default {
	abilities: [
		{ "name": "HTML, xHTML, MD, SVG, XML, …", "year": 1999 },
		{ "name": "CSS, SCSS, … (pre-processors)", "year": 1999 },
		{ "name": "Javascript & ES6", "year": 2001 },
		{ "name": "Typescript", "year": 2022 },
		{ "name": "React & JSX", "year": 2019 },
		{ "name": "NodeJS & ExpressJS", "year": 2013 },
		{ "name": "HTTP & RESTful APIs", "year": 2013 },
		{ "name": "WebSockets", "year": 2020 },
		{ "name": "Redux", "year": 2019 },
		{ "name": "NextJS, Webpack, Gulp (package builders)", "year": 2017 },
		{ "name": "jQuery", "year": 2005 },
		{ "name": "DAPP (blockchain, MetaMask, Web3.js, Ganache, …)", "year": 2022 },
		{ "name": "Styled components, Material UI", "year": 2022 },
		{ "name": "Oracle", "year": 2002 },
		{ "name": "Microsoft SQL Server, MySQL, PostgreSQL, …", "year": 2005 },
		{ "name": "Neo4J & Cypher", "year": 2013 },
		{ "name": "E2E: Playwright, …", "year": 2023 },
		{ "name": "Unitary: Jest, Mocha, …", "year": 2017 }, // Chai, Sinon
		{ "name": "Git & SVN", "year": 2005 },
		{ "name": "Monorepo PNPM", "year": 2022 },
		{ "name": "Jenkins/GoCD", "year": 2017 },
		{ "name": "AWS: ECS, EC2, DynamoDB, Lambda, …", "year": 2013 },
		{ "name": "Telemetrics: Splunk, NewRelic", "year": 2019 },
		{ "name": "Bash", "year": 2015 },
		{ "name": "Linux / MacOS", "year": 2011 },
		// { "name": "Windows Server", "year": 2002 },
		{ "name": "Adobe applications", "year": 1997 },
		// { "name": "Apache & Nginx", "year": 2001 },
		// { "name": "Microsoft .Net C#", "year": 2006 },
		// { "name": "PHP", "year": 2004 },
		// { "name": "Excel / Spreadsheets", "year": 2002 }
	],
	experience: {
		data: [
			/* {
				company: '',
				period: {
					start: [0, 0],
					end: [0, 0],
				},
				title: '',
				sector: '',
				about: '',
				clients: [],
				attributions: [],
				achievements: [],
				technologies: [],
			}, */
			{
				company: 'Applied Blockchain',
				period: {
					start: [1, 2022],
					end: [4, 2024],
				},
				title: 'Fullstack Senior Web Developer',
				sector: 'blockchain technology',
				about: 'Specialized in DeFi, Web3, cryptocurrency, and financial services, offering blockchain solutions across industries like energy, supply chain, telecommunications, and retail',
				clients: [
					<>Shell</>,
					<>Mishcon del Reya</>,
					<>UppFirst</>,
				],
				attributions: [
					<>Develop dApps that integrate blockchain features like wallet support and NFT rendering</>,
					<>Ensure accurate cryptocurrency calculations with multi-decimal values (satoshis/gweis)</>,
					<>Collaborate with designers to achieve pixel-perfect layouts</>,
					<>Coordinate with global teams across different time zones and cultures</>,
					<>Present technical progress to clients, addressing questions and discussing next steps</>,
				],
				achievements: [
					<>Developed a dApp for a custom cryptocurrency focused on green causes, with features such as minting, airdrop, and coin swaps, along with an admin app for managing the currency</>,
					<>Built an e-commerce platform linked to NFTs, emphasizing responsive design and detailed layout rendering</>,
					<>Added and maintained features for a real-time energy trading application, including CSV parsing and product expiry controls</>,
					<>Recreated the company's static website using a WYSIWYG tool for better team collaboration</>,
				],
				technologies: [
					<>React</>,
					<>Typescript</>,
					<>Next</>,
					<>SQL and TypeORM</>,
					<>MUI (Material UI) and Styled components</>,
					<>Web3.js, bn.js</>,
					<>Metamask and Phantom wallets</>,
					<>Truffle suit with Ganache</>,
					<>Jest and Playwright</>,
				],
			},
			{
				company: 'PagSeguro',
				period: {
					start: [10, 2016],
					end: [1, 2022],
				},
				title: 'Senior frontend software engineer',
				sector: 'financial services',
				about: 'PagSeguro offers innovative solutions in financial services and means of payment, automating the purchase, sale and wiring process in a simple and secure manner',
				clients: [],
				attributions: [
					<>Implement high-quality web solutions using modern frameworks</>,
					<>Collaborate with backend developers to integrate frontend solutions</>,
					<>Deploy and maintain applications in cloud environments</>,
					<>Work closely with product owners to plan and develop solutions</>,
					<>Plan and execute agile roadmaps using Scrum and Kanban</>,
					<>Mentor team members through pair programming and code reviews</>,
					<>Collaborate with UI/UX teams to create user-friendly designs</>,
					<>Support and refactor monolithic legacy systems</>,
				],
				achievements: [
					<>Developed UIs for managing payment subscriptions using Apache Velocity</>,
					<>Designed a back-office system for customer segmentation and tax management</>,
					<>Built a payment link service using NodeJS and React</>,
					<>Developed and maintained a new sandbox website for developer tools</>,
					<>Added new payment methods to the legacy checkout system</>,
					<>Implemented a WebSockets pooling solution for real-time payment status</>,
				],
				technologies: [
					<>HTML5, JSX, Handlebars, Apache Velocity Template Language (VTL)</>,
					<>CSS, SCSS, BEM</>,
					<>Javascript: React, Redux, NodeJS, ES6, JSON, jQuery</>,
					<>NodeJS: ExpressJS for BFF (backend for frontend) and RESTfull API development</>,
					<>TDD: test-driven development with Jest, Mocha, Chai, Sinon</>,
					<>Package builders: Webpack, NextJS, Gulp</>,
					<>Git, Atlassian Stash/BitBucket</>,
					<>DevOps: Jenkins, GoCD, Apache Mesos, Docker</>,
					<>AWS: ECS, EC2, DynamoDB</>,
					<>Telemetrics: Splunk, NewRelic</>,
					<>Patterns and methodologies: domain-driven design, Kanban, agile</>,
				],
			},
			{
				company: 'x128',
				period: {
					start: [10, 2014],
					end: [9, 2016],
				},
				title: 'CEO and founder',
				sector: 'Software design and consulting',
				about: '',
				clients: [
					<>Olé Studio</>,
					<>ClickBebe</>,
					<>Alumicentro</>,
					<>Polycom</>,
					<>Promoção Relâmpago Passagens</>,
					<>Mercovino/Brindisi</>,
					<>Changepoint</>,
					<>Itaú</>,
					<>Akua</>,
					<>Ornitorrinco</>,
					<>ReachLocal</>,
					<>Agilizeware</>,
				],
				attributions: [],
				achievements: [
					<>Integrated and customized a content management system (CMS), product catalog and payment checkout, chat rooms with high-audience and auto-scalable infrastructure, user forums, self-service announcements editor for buying and selling goods</>,
					<>Built a customer relationship management (CMS) and enterprise resource planning (ERP) for a metallurgic goods reseller</>,
					<>Developed a data mining tool to search for airline tickets best prices</>,
					<>Built, deployed and maintained several e-commerce websites for different publics: fashion, beverage, pregnant/lactating woman and many others</>,
					<>Integrated a governance software for Itaú bank using the canadian governance solution ChangePoint</>,
				],
				technologies: [
					<>NodeJS</>,
					<>PHP</>,
					<>Microsoft .Net with C# using SVN</>,
					<>Ruby on Rails</>,
					<>MySQL</>,
					<>Wordpress with Woocommerce (providing plugin integration, creation and customization)</>,
					<>AWS ECS with auto-scaling</>,
					<>Git and GitLab</>,
					<>Changepoint governance software</>,
				],
			},
			{
				company: 'Nicsware',
				period: {
					start: [7, 2013],
					end: [7, 2014],
				},
				title: 'Software architect',
				sector: 'Healthcare software startup',
				about: '',
				clients: [],
				attributions: [],
				achievements: [
					<>Developed a medical record software with flexible form editor, clinical schedule, extensible patient contacts record system; with sharing features between physicians protected via ACL</>,
					<>Built a framework with web server in Javascript/NodeJS using graphical database Neo4J as data storage; all communication pipelines in JSON and responsive layout</>,
					<>Created a business plan including financial planning, marketing strategy and selling support materials</>,
				],
				technologies: [
					<>HTML</>,
					<>CSS</>,
					<>jQuery</>,
					<>NodeJS</>,
					<>Neo4J graphical database</>,
					<>AWS</>,
				],
			},
			{
				company: 'Neoris',
				period: {
					start: [6, 2011],
					end: [7, 2013],
				},
				title: 'Senior system integration consultant',
				sector: 'Software consulting services',
				about: '',
				clients: [
					<>Usiminas</>,
					<>Vale</>,
					<>Gerdau</>,
					<>Videolar</>,
					<>Eternit</>,
				],
				attributions: [],
				achievements: [
					<>Developed software for production lines for large factories with special focus in OEE (overall equipment efficency): charts showing the machinery maintenance stop summary and staff production performance</>,
					<>Upgraded the routing layout of the videowall, a panel measuring 16.6×9.3 meters atthe control center that monitors 24×7 allthe processes of a large-scale siderurgical plant</>,
					<>Created HDTV dashboards for the port operations tower that controlls the ship’s parking, load and unload</>,
				],
				technologies: [
					<>SAP MII</>,
					<>Javascript</>,
					<>.Net C#</>,
					<>HTML</>,
					<>CSS</>,
					<>XML</>,
					<>XSLT</>,
					<>XSD</>,
					<>xPath</>,
				],
			},
			{
				company: 'Telefonica',
				period: {
					start: [8, 2008],
					end: [4, 2011],
				},
				title: 'Software architect',
				sector: 'Large scale telecomunications',
				about: '',
				clients: [],
				attributions: [],
				achievements: [
					<>Created a portal with several applications connected to a great deal of data sources for managing installation and repair in telecommunications landlines of corporate customers</>,
					<>Integrated several databases (Oracle, Microsoft SQL Server, MySQL, …) for online analytical processing (OLAP)</>,
					<>Built a PHP framework using MVC pattern with a UIX interactive styleguide</>,
				],
				technologies: [
					<>HTML</>,
					<>CSS</>,
					<>Javascript</>,
					<>jQuery</>,
					<>JSON</>,
					<>Microsoft SQL Server</>,
					<>Oracle</>,
					<>MySQL</>,
					<>PostgreSQL</>,
					<>Windows Server management</>,
				],
			},
			{
				company: 'FastCash',
				period: {
					start: [9, 2006],
					end: [8, 2008],
				},
				title: 'Software architect and tech lead',
				sector: 'Virtual currency platform for micro finances',
				about: '',
				clients: [],
				attributions: [],
				achievements: [
					<>Developed a micro payment gateway system for all payment options available in Brazil, alongside its conciliation logic and digital product delivery: pincodes or electronic credit in partner systems</>,
					<>Coded deep processual changes in the e-commerce platform, like product composition, checkout process and physical with virtual stock management</>,
					<>Created an extranet platform for integrated business partners to existing cloud systems for sales and management of digital goods</>,
				],
				technologies: [
					<>Microsoft ASP & IIS</>,
					<>Automated bots using Microsoft RDC</>,
					<>HTML & CSS</>,
					<>Microsoft SQL Server</>,
					<>Microsoft .Net</>,
					<>Windows Server management</>,
				],
			},
			{
				company: 'IBM',
				period: {
					start: [8, 2005],
					end: [7, 2006],
				},
				title: 'Quality assurance specialist',
				sector: 'Technology services and hardware',
				about: '',
				clients: [],
				attributions: [],
				achievements: [
					<>quality assurance on the website IBM.com (all americas) and intranet W3 (USA)</>,
					<>deployed a skill mapping tool to gather staff abilities and their allocation in projects</>,
				],
				technologies: [
					<>HTML & CSS</>,
					<>Javascript & AJAX</>,
					<>PHP</>,
					<>WebKing</>,
				],
			},
			{
				company: 'IBEX',
				period: {
					start: [11, 2004],
					end: [8, 2005],
				},
				title: 'Frontend developer and UIX designer',
				sector: 'Digital agency',
				about: '',
				clients: [
					<>Telefonica</>,
					<>Gerdau</>,
					<>Bridgestone/Firestone</>,
					<>Alliance consultoria</>,
				],
				attributions: [],
				achievements: [
					<>Rebuilt the game framework for corporate incentive campaigns with greater modularity, such as skins, score by time or accuracy and many other features</>,
					<>Built a CMS for user-customizable websites</>,
					<>Worked on visual identity for products</>,
				],
				technologies: [
					<>HTML & CSS</>,
					<>Javascript</>,
					<>PostgreSQL</>,
					<>Adobe Flash using AFLEX (AJAX for Flash)</>,
				],
			},
			{
				company: 'Santander',
				period: {
					start: [6, 2003],
					end: [11, 2004],
				},
				title: 'Software architect',
				sector: 'Worldwide banking and financial services',
				about: '',
				clients: [],
				attributions: [],
				achievements: [
					<>Developed a web application for a diversity of financial dashboards, all deeply customizable</>,
					<>Prototyped a continental intranet with financial reports, news, documents, photos and more</>,
					<>Created several management tools, like task status, meeting schedule, document repository, webchat, …</>,
				],
				technologies: [
					<>HTML & CSS</>,
					<>Javascript</>,
					<>Microsoft ASP & IIS</>,
					<>Excel integration</>,
				],
			},
			{
				company: 'Chris Cintos',
				period: {
					start: [12, 2000],
					end: [11, 2002],
				},
				// <!>
				title: 'Software developer',
				sector: 'Manufacturer of high-quality seat belts for the automotive industry',
				about: '',
				clients: [],
				attributions: [],
				achievements: [
					<>Developed an intranet application with several modules, including human resources, help desk, project management, training, etc.</>,
					<>Created the company's institutional website</>,
				],
				technologies: [
					<>HTML & CSS</>,
					<>Javascript</>,
					<>Microsoft ASP & IIS</>,
					<>Oracle RDBMS</>,
				],
			},
		],
	},
};

// -----------------------------------------------------------------------------
